/**
 * @file lexer.cpp
 * @author Carlos Salguero
 * @author Sergio Garnica
 * @brief Implementation of the Lexer class
 * @version 0.1
 * @date 2023-05-12
 *
 * @copyright Copyright (c) 2023
 *
 */

// Standard libraries
#include <iostream>
#include <fstream>
#include <filesystem>
#include <regex>

// Project files
#include "lexer.h"
#include "csharp_language.h"

// Access Methods
/**
 * @brief
 * Gets the tokens generated by the lexer
 * @return std::vector<Token> Vector of tokens
 */
std::vector<Token> Lexer::get_tokens() const
{
    return m_tokens;
}

// Methods (Public)
/**
 * @brief
 * Starts the lexing of the files
 * @param filenames Vector of filenames
 */
void Lexer::start_lexing(const std::vector<std::string> &filenames)
{
    try
    {
        for (const auto &filename : filenames)
        {
            auto tokens = lex_file(filename);
            save(filename, tokens);
        }
    }
    catch (std::exception &e)
    {
        throw std::runtime_error(e.what());
    }
}

/**
 * @brief
 * Saves the tokens in a HTML file
 * @param filename Filename to save the tokens
 * @throw std::runtime_error If the file cannot be opened
 */
void Lexer::save(const std::string &filename, const std::vector<Token> &tokens) const
{
    try
    {
        std::string output_filename = get_output_filename(filename);
        std::ofstream output_file(output_filename);
        if (!output_file)
        {
            throw std::runtime_error("Cannot open file: " + output_filename);
        }

        output_file << generate_html(tokens);
        output_file.close();
    }
    catch (std::exception &e)
    {
        throw std::runtime_error(e.what());
    }
}

// Methods (Private)
/**
 * @brief
 * Lex the files with parallel threads
 * @param filenames Vector of filenames
 */
void Lexer::lex(const std::vector<std::string> &filenames)
{
    try
    {
        for (const auto &filename : filenames)
            m_threads.emplace_back(&Lexer::lex_file, this,
                                   filename);

        for (auto &thread : m_threads)
            thread.join();
    }

    catch (std::exception &e)
    {
        throw std::runtime_error(e.what());
    }
}

/**
 * @brief
 * Lex a file and generate the tokens for said file
 * @param filename Filename to lex
 * @throw std::runtime_error If the file cannot be opened
 */
std::vector<Token> Lexer::lex_file(const std::string_view &filename)
{
    try
    {
        std::ifstream input_file(filename.data(),
                                 std::ios::in | std::ios::binary);

        if (!input_file)
        {
            throw std::runtime_error("Cannot open file: " + std::string(filename));
        }

        std::string buffer((std::istreambuf_iterator<char>(input_file)),
                           std::istreambuf_iterator<char>());

        input_file.close();

        if (buffer.empty())
            throw std::runtime_error("File is empty: " + std::string(filename));

        return tokenize(buffer);
    }
    catch (std::exception &e)
    {
        throw std::runtime_error(e.what());
    }
}

/**
 * @brief
 * Tokenizes the source code and generates the html code.
 * @param buffer Source code to tokenize
 * @return std::vector<Token> Vector of html code
 * @throw std::runtime_error If the file cannot be opened
 */
std::vector<Token> Lexer::tokenize(const std::string_view &buffer)
{
    try
    {
        std::vector<Token> tokens;

        // Token for identifying parenthesis, brackets, semicolon
        std::regex tokenRegex("([{};])");

        std::string bufferStr(buffer);
        std::sregex_token_iterator iter(bufferStr.begin(), bufferStr.end(),
                                        tokenRegex, -1);
        std::sregex_token_iterator end;

        while (iter != end)
        {
            std::string token = *iter++;

            if (token.empty())
                continue;

            TokenType tokenType = identify_token(token);

            if (tokenType == TokenType::Comment)
            {
                std::regex commentRegex("([/][/*].*?[*][/])");
                std::smatch match;
                std::regex_search(token, match, commentRegex);
                token = match.str();
            }

            tokens.emplace_back(token, tokenType);
        }
        return tokens;
    }
    catch (std::exception &e)
    {
        throw std::runtime_error(e.what());
    }
}

/**
 * @brief
 * Identify the token type based of the Token class
 * @param token Token to identify
 * @return TokenType Type of the token
 */
TokenType Lexer::identify_token(const std::string_view &token)
{
    if (std::find(csharp::m_keywords.begin(),
                  csharp::m_keywords.end(), token) !=
        csharp::m_keywords.end())
        return TokenType::Keyword;

    else if (std::find(csharp::m_operators.begin(),
                       csharp::m_operators.end(), token) !=
             csharp::m_operators.end())
        return TokenType::Operator;

    else if (std::find(csharp::m_separators.begin(),
                       csharp::m_separators.end(), token) !=
             csharp::m_separators.end())
        return TokenType::Separator;

    else if (std::find(csharp::m_comments.begin(),
                       csharp::m_comments.end(), token) !=
             csharp::m_comments.end())
        return TokenType::Comment;

    else if (std::find(csharp::m_literals.begin(),
                       csharp::m_literals.end(), token) != csharp::m_literals.end())
        return TokenType::Literal;

    else if (std::find(csharp::m_preprocessor.begin(),
                       csharp::m_preprocessor.end(), token) !=
             csharp::m_preprocessor.end())
        return TokenType::Preprocessor;

    else if (std::find(csharp::m_contextual_keywords.begin(),
                       csharp::m_contextual_keywords.end(),
                       token) != csharp::m_contextual_keywords.end())
        return TokenType::ContextualKeyword;

    else if (std::find(csharp::m_access_specifiers.begin(),
                       csharp::m_access_specifiers.end(), token) !=
             csharp::m_access_specifiers.end())
        return TokenType::AccessSpecifier;

    else if (std::find(csharp::m_attribute_targets.begin(),
                       csharp::m_attribute_targets.end(), token) !=
             csharp::m_attribute_targets.end())
        return TokenType::AttributeTarget;

    else if (std::find(csharp::m_attribute_usage.begin(),
                       csharp::m_attribute_usage.end(), token) !=
             csharp::m_attribute_usage.end())
        return TokenType::AttributeUsage;

    else if (std::find(csharp::m_escaped_identifiers.begin(),
                       csharp::m_escaped_identifiers.end(),
                       token) != csharp::m_escaped_identifiers.end())
        return TokenType::EscapedIdentifier;

    else if (std::find(csharp::m_interpolated_strings.begin(),
                       csharp::m_interpolated_strings.end(),
                       token) != csharp::m_interpolated_strings.end())
        return TokenType::InterpolatedStringLiteral;

    else if (std::find(csharp::m_nullables.begin(),
                       csharp::m_nullables.end(), token) !=
             csharp::m_nullables.end())
        return TokenType::NullLiteral;

    else if (std::find(csharp::m_verbatim_strings.begin(),
                       csharp::m_verbatim_strings.end(), token) !=
             csharp::m_verbatim_strings.end())
        return TokenType::VerbatimStringLiteral;

    return TokenType::Other;
}

/**
 * @brief
 * Converts the tokens to html code. Uses the style.css defined classes
 * to color the tokens
 * @param tokens Tokens to convert
 * @return std::string Html code
 */
std::string Lexer::token_to_html(const Token &token) const
{
    std::string html;

    switch (token.get_type())
    {
    case TokenType::Keyword:
        html += "<span class=\"Keyword\">" + token.get_value() + "</span>";
        break;

    case TokenType::Identifier:
        html += "<span class=\"Identifier\">" + token.get_value() + "</span>";
        break;

    case TokenType::Literal:
        html += "<span class=\"Literal\">" + token.get_value() + "</span>";
        break;

    case TokenType::Operator:
        html += "<span class=\"Operator\">" + token.get_value() + "</span>";
        break;

    case TokenType::Separator:
        html += "<span class=\"Separator\">" + token.get_value() + "</span>";
        break;

    case TokenType::Comment:
        html += "<span class=\"Comment\">" + token.get_value() + "</span>";
        break;

    case TokenType::Preprocessor:
        html += "<span class=\"Preprocessor\">" + token.get_value() + "</span>";
        break;

    case TokenType::ContextualKeyword:
        html += "<span class=\"ContextualKeyword\">" + token.get_value() + "</span>";
        break;

    case TokenType::AccessSpecifier:
        html += "<span class=\"AccessSpecifier\">" + token.get_value() + "</span>";
        break;

    case TokenType::AttributeTarget:
        html += "<span class=\"AttributeTarget\">" + token.get_value() + "</span>";
        break;

    case TokenType::AttributeUsage:
        html += "<span class=\"AttributeUsage\">" + token.get_value() + "</span>";
        break;

    case TokenType::EscapedIdentifier:
        html += "<span class=\"EscapedIdentifier\">" + token.get_value() + "</span>";
        break;

    case TokenType::InterpolatedStringLiteral:
        html += "<span class=\"InterpolatedStringLiteral\">" + token.get_value() + "</span>";
        break;

    case TokenType::NullLiteral:
        html += "<span class=\"NullLiteral\">" + token.get_value() + "</span>";
        break;

    case TokenType::VerbatimStringLiteral:
        html += "<span class=\"VerbatimStringLiteral\">" + token.get_value() + "</span>";
        break;

    case TokenType::RegularExpressionLiteral:
        html += "<span class=\"RegularExpressionLiteral\">" + token.get_value() + "</span>";
        break;

    case TokenType::NumericLiteral:
        html += "<span class=\"NumericLiteral\">" + token.get_value() + "</span>";
        break;

    case TokenType::Other:
        html += "<span class=\"Other\">" + token.get_value() + "</span>";
        break;
    }

    return html;
}

/**
 * @brief
 * Generates the HTML code from the tokens vector
 * @param tokens Tokens to convert
 * @return std::string Html code
 */
std::string Lexer::generate_html(const std::vector<Token> &tokens) const
{
    std::string html;

    html += "<!DOCTYPE html>\n";
    html += "<html lang=\"en\">\n";
    html += "<head>\n";
    html += "<meta charset=\"UTF-8\">\n";
    html += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
    html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
    html += "<title>Highlighter</title>\n";
    html += "<link rel=\"stylesheet\" href=\"../src/styles/styles.css\">\n";
    html += "</head>\n";
    html += "<body style=\"background-color: var(--background-color);\">\n";
    html += "<pre><code>\n";

    int indentationLevel = 0;
    std::string indentation(indentationLevel * 2, ' ');
    bool previousTokenWasNewLine = false;

    // Writing the tokens to the html file
    for (const auto &token : tokens)
    {
        if (token.get_type() == TokenType::Separator &&
            token.get_value() == ";")
        {
            html += "\n";
            html += indentation;
            previousTokenWasNewLine = true;
        }

        else if (previousTokenWasNewLine &&
                 token.get_type() == TokenType::Separator &&
                 token.get_value() == ";")
        {
            html += token_to_html(token) + "\n";
            html += indentation;
            previousTokenWasNewLine = true;
            continue;
        }

        else if (token.get_type() == TokenType::Separator && token.get_value() == "\t")
        {
            html += "&emsp;";
            previousTokenWasNewLine = false;
        }
        else if (token.get_type() == TokenType::Separator && token.get_value() == " ")
        {
            html += "&nbsp;";
            previousTokenWasNewLine = false;
        }
        else if (token.get_type() == TokenType::Comment)
        {
            html += "<br>\n";
            html += indentation;
            html += token_to_html(token);
            html += "<br>\n";
            html += indentation;
            previousTokenWasNewLine = true;
        }
        else
        {
            html += token_to_html(token);
            previousTokenWasNewLine = false;
        }

        if (token.get_type() == TokenType::Separator && token.get_value() == "{")
        {
            html += "\n";
            indentationLevel++;
            indentation = std::string(indentationLevel * 2, ' ');
            html += indentation;
            previousTokenWasNewLine = true;
        }
        else if (token.get_type() == TokenType::Separator && token.get_value() == "}")
        {
            html += "\n";
            indentationLevel--;
            indentation = std::string(indentationLevel * 2, ' ');
            html += indentation;
            previousTokenWasNewLine = true;
        }
    }

    html += "</code></pre>\n";
    html += "</body>\n";
    html += "</html>\n";

    return html;
}

/**
 * @brief
 * Gets the output filename from the input filename
 * @param inputFilename Input filename
 * @return std::string Output filename
 */
std::string Lexer::get_output_filename(const std::string &inputFilename) const
{
    std::filesystem::path path(inputFilename);
    std::string filename = path.stem().string();
    std::filesystem::path outputPath = "../outputParallel/" + filename + ".html";

    return outputPath.string();
}